# Generated by Django 3.2.2 on 2021-05-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alexa', models.CharField(default='', max_length=60)),
                ('alpha', models.FloatField(default=4)),
                ('beta', models.FloatField(default=4)),
                ('halflife', models.FloatField(default=24)),
                ('lastTest', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
